name: Product Scraper CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: pytest -q --maxfail=1 --junitxml=report.xml

      - name: Upload pytest report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report.xml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      # THIS IS THE CORRECTED STEP
      - name: Deploy to Render
        uses: Render/action-deploy@v1
        with:
          # Your unique ID for the service you create on Render
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          # Your API key for Render
          api-key: ${{ secrets.RENDER_API_KEY }}